/**
 * Test stub for `virtual:pwa-register/react`. The real module is generated by
 * vite-plugin-pwa at build time and does not exist under Vitest, so the PWA
 * test project aliases this file in its place (see vitest.config.ts).
 */
import { useState } from 'react'

export function useRegisterSW() {
  const needRefresh = useState(false)
  const offlineReady = useState(false)
  return {
    needRefresh,
    offlineReady,
    updateServiceWorker: async (_reloadPage?: boolean) => {},
  }
}
