import { fileURLToPath } from 'node:url'
import react from '@vitejs/plugin-react'
import { defineConfig } from 'vitest/config'

// One Vitest run covers all three workspaces (CLAUDE.md: "npm test — vitest
// (pwa + sidecar + shared)"). Projects keep the environments apart: the PWA
// needs jsdom, the pure domain logic and the sidecar do not.
export default defineConfig({
  test: {
    projects: [
      {
        test: {
          name: 'shared',
          root: './packages/shared',
          environment: 'node',
          include: ['src/**/*.test.ts'],
        },
      },
      {
        plugins: [react()],
        resolve: {
          alias: {
            // Generated by vite-plugin-pwa at build time; absent under Vitest.
            'virtual:pwa-register/react': fileURLToPath(
              new URL('./apps/pwa/test/stubs/pwa-register.ts', import.meta.url),
            ),
          },
        },
        test: {
          name: 'pwa',
          root: './apps/pwa',
          environment: 'jsdom',
          setupFiles: ['./test/setup.ts'],
          include: ['src/**/*.test.{ts,tsx}', 'test/**/*.test.{ts,tsx}'],
          exclude: ['test/e2e/**'],
        },
      },
      {
        test: {
          name: 'sidecar',
          root: './apps/push-sidecar',
          environment: 'node',
          include: ['src/**/*.test.ts'],
        },
      },
    ],
  },
})
