#!/usr/bin/env bash
# Copies the gateway's `?key=` unlock guard into the host-only file that the /m/
# location includes. Called by install.sh; RUN ON THE VPS.
#
#   extract-unlock.sh <vhost> <dest>
#
# The guard is searched for in the vhost AND every file it includes: on the
# live host it is not in the vhost at all but in
# /etc/nginx/snippets/cezar-gate.conf, which `location /` includes — the vhost
# itself is rewritten verbatim by `cezar server-install`. Glob includes and our
# own cezar-mobile* snippets are skipped.
#
# Why a copy: the guard lives inside the vhost's `location /`, and `^~ /m/`
# takes /m/ away from that block, so /m/?key=… never reaches it and the
# installed app cannot unlock itself. The guard holds the access secret, so the
# repo cannot carry it (CLAUDE.md rule 6) — it is copied verbatim, on the host,
# into a mode-600 file. This script never prints it.
#
# Exit 0: written. Exit 3: not exactly one guard found, or it does not look
# like one — nothing written, and nothing guessed.
set -euo pipefail

vhost="${1:?usage: $0 <vhost> <dest>}"
dest="${2:?usage: $0 <vhost> <dest>}"

sources=("$vhost")
while IFS= read -r inc; do
  [[ "$inc" == *[*?[]* || "$(basename "$inc")" == cezar-mobile* ]] && continue
  [[ -f "$inc" ]] && sources+=("$inc")
done < <(sed -nE 's/^[[:space:]]*include[[:space:]]+([^;[:space:]]+)[[:space:]]*;.*/\1/p' "$vhost")

# The `if ($arg_key = …) { … }` block, verbatim, tracked by brace depth so a
# `{` on the following line still works. Commented-out copies are skipped. The
# `if` must open its own line and the block must close exactly: a guard sharing
# a line with `location / {` would drag that in too, and a nested `location /`
# inside /m/ does not pass `nginx -t`. Refusing is better than trimming.
block=$(awk '
  !grab && /^[[:space:]]*if[[:space:]]*\([[:space:]]*\$arg_key[[:space:]]*=/ {
    grab = 1; depth = 0; found++
  }
  grab {
    print
    depth += (split($0, _o, "{") - 1) - (split($0, _c, "}") - 1)
    if (depth < 0) bad = 1
    if (depth <= 0 && index($0, "}") > 0) grab = 0
  }
  END { if (found != 1 || bad || grab) exit 3 }
' "${sources[@]}") || exit 3

# It must be the unlock guard and not some other test of the same argument.
grep -q 'Set-Cookie' <<<"$block" || exit 3
grep -qE 'return[[:space:]]+30[12]' <<<"$block" || exit 3

mkdir -p "$(dirname "$dest")"
umask 077
tmp=$(mktemp "$dest.XXXXXX")
{
  echo "# Generated by deploy/nginx/extract-unlock.sh from: ${sources[*]}"
  echo "# Holds the access secret: never commit, copy or print this file."
  echo "$block"
} >"$tmp"
chmod 600 "$tmp"
mv -f "$tmp" "$dest"
