#!/usr/bin/env bash
# Writes the perimeter's sign-out (S-12, FR-006): `POST /m/session/end` answers
# 204 with a Set-Cookie that expires the gate's session cookie. Called by
# install.sh after extract-unlock.sh; RUN ON THE VPS.
#
#   signout-from-unlock.sh <unlock-file> <dest>
#
# Why the perimeter: the session is an HttpOnly cookie the app cannot read or
# delete, and Cezar has no sign-out (it has no sign-in). Expiring a cookie needs
# only its name and Path — not its value — so the endpoint carries no secret.
# The name is not in this repo either, because it is the gate's to choose: it
# is read off the Set-Cookie in the unlock guard that extract-unlock.sh copied.
# The guard's line does hold the secret; this script keeps it in a variable and
# never prints it.
#
# Only POST, and only from this origin: a GET (a prefetch, a pasted link) or a
# cross-site form must not sign the operator out.
#
# Exit 0: written. Exit 3: no usable Set-Cookie in the unlock file — nothing
# written, and nothing guessed.
set -euo pipefail

unlock="${1:?usage: $0 <unlock-file> <dest>}"
dest="${2:?usage: $0 <unlock-file> <dest>}"
[[ -r "$unlock" ]] || exit 3

cookie=$(grep -m1 -oE 'Set-Cookie[[:space:]]+"[^"]*"' "$unlock") || exit 3
name=$(sed -nE 's/^Set-Cookie[[:space:]]+"([A-Za-z0-9_.-]+)=.*/\1/p' <<<"$cookie")
[[ -n "$name" ]] || exit 3
path=$(sed -nE 's/.*;[[:space:]]*[Pp]ath=([^;"[:space:]]+).*/\1/p' <<<"$cookie")
path="${path:-/}"
# A Secure cookie can only be replaced by a Secure one, and a plain one should
# stay plain (the rehearsal runs over http).
secure=""
grep -qiE ';[[:space:]]*Secure([;"[:space:]]|$)' <<<"$cookie" && secure="; Secure"

csp="default-src 'self'; connect-src 'self'; img-src 'self' data: blob:; style-src 'self' 'unsafe-inline'; base-uri 'self'; frame-ancestors 'none'"

mkdir -p "$(dirname "$dest")"
tmp=$(mktemp "$dest.XXXXXX")
cat >"$tmp" <<CONF
# Generated by deploy/nginx/signout-from-unlock.sh from: $unlock
# The gate cookie's name only — no secret. Included inside \`location ^~ /m/\`.
location = /m/session/end {
    # Nested: repeat the parent's security headers (see cezar-mobile.conf).
    add_header Content-Security-Policy "$csp" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Cache-Control "no-store" always;
    # Through a variable, set only past both checks: an \`if\` block inherits
    # this location's add_header, so a literal Set-Cookie here would ride on the
    # 405 and the 403 too. An empty value is not sent at all.
    set \$cezar_signout "";
    if (\$request_method != POST) {
        return 405;
    }
    if (\$http_origin != "\$scheme://\$http_host") {
        return 403;
    }
    set \$cezar_signout "$name=; Path=$path; Max-Age=0; Expires=Thu, 01 Jan 1970 00:00:00 GMT$secure; HttpOnly; SameSite=Lax";
    add_header Set-Cookie \$cezar_signout always;
    return 204;
}
CONF
chmod 644 "$tmp"
mv -f "$tmp" "$dest"
